# Generated by Django 5.1.1 on 2024-10-28 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='post',
            name='audio_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='location_description',
        ),
    ]
