# Generated by Django 5.1.1 on 2024-10-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password1',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password2',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
