# Generated by Django 5.1.1 on 2024-10-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_userprofile_password1_userprofile_password2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='password2',
        ),
    ]
