# Generated by Django 5.1.1 on 2024-10-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_userprofile_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='password1',
            new_name='password',
        ),
    ]
