# Generated by Django 5.1.1 on 2024-10-20 12:04

import apps.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_alter_userprofile_email_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='all_media/', validators=[apps.models.CustomFileExtensionValidator(('mp4', 'mkv', 'avi', 'webm', '3gp', 'jpg', 'jpeg', 'png', 'webp', 'mov'))])),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=222, null=True)),
                ('text', models.TextField(blank=True, default="bu erda siz o'ylagan ibora bor", null=True)),
                ('alt_text', models.TextField(blank=True, null=True)),
                ('image_description', models.TextField(blank=True, null=True)),
                ('location_description', models.TextField(blank=True, null=True)),
                ('audio_description', models.TextField(blank=True, null=True)),
                ('media', models.ManyToManyField(related_name='posts', to='apps.media')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_tags', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
